#+TITLE:       Alex Ott's Page. Новости сайта
#+SUBTITLE:    Новости сайта
#+BLOG_URL:    http://xtalk.msk.su/~ott/ru/news/
#+PUBLISH_DIR: /home/ott/projects/my-page-muse/ru/news/
#+ENCODING:    utf-8
#+LANGUAGE:    ru
#+FEED_TYPE:   atom
#+HOMEPAGE:    http://xtalk.msk.su/~ott/ru/
#+KEYWORDS:    alex ott blog news articles emacs новости статьи емакс программирование
#+HTML_CSS:    web.css

* DONE Добавлен рассказ про работу с Cedet                 :emacs:article:cedet:
  CLOSED: [2009-02-02 Mon 21:04]

К статье [[http://xtalk.msk.su/~ott/ru/writings/emacs-devenv/][Emacs как рабочее средство разработчика ПО]] добавлен [[http://xtalk.msk.su/~ott/ru/writings/emacs-devenv/EmacsCedet.html][рассказ про работу с пакетом
Cedet]].  Это первая версия рассказа, которая будет в дальнейшем развиваться.

* DONE Обновлен рассказ про Emacs и Git                      :emacs:article:git:
  CLOSED: [2008-11-19 Wed 15:18]

Статья про [[http://xtalk.msk.su/~ott/ru/writings/emacs-vcs/EmacsGit.html][Emacs & Git]] была сильно обновлена -- добавлены описания пакетов git-emacs,
magit и некоторых вспомогательных пакетов

* DONE Рассказ про пакет aHg                           :emacs:article:mercurial:
  CLOSED: [2008-10-13 Mon 16:38]

В рассказ про работу с Mercurial добавил [[http://xtalk.msk.su/~ott/ru/writings/emacs-vcs/EmacsMercurial.html#sec5][раздел про пакет aHg]]

* DONE Окончательная версия статьи про Emacs и Erlang     :emacs:erlang:article:
  CLOSED: [2008-08-25 Mon 13:09]

Закончил статью про [[http://xtalk.msk.su/~ott/ru/writings/emacs-devenv/EmacsErlang.html][использование Emacs для разработки на языке Erlang]]. Замечания и
предложения приветствуются

* DONE Вторая бета статьи про Emacs и Erlang              :emacs:erlang:article:
  CLOSED: [2008-08-21 Thu 15:09]

Обновил статью про использование Emacs для работы с Erlang.  Добавились описания distel &
erlware-mode...

* DONE Драфт статьи про Emacs и Erlang                    :emacs:erlang:article:
  CLOSED: [2008-08-06 Wed 15:27]

выложил на сайт драфт [[http://xtalk.msk.su/~ott/ru/writings/emacs-devenv/EmacsErlang.html][статьи про работу с Erlang в Emacs]]. В следующей вресии будет
добавлено описание erlware-mode и distel.

* DONE Прикрутил к сайту ленту новостей через blorg                 :site:emacs:
  CLOSED: [2008-08-04 Mon 12:32]

С помощью [[http://lumiere.ens.fr/~guerry/u/blorg.html][blorg]] прикрутил к сайту публикацию ленты новостей из файлов org-mode.  Так что
можете подписаться и получать новости об обновлениях статей и т.п.  Ссылки на
соответствующие ленты находятся на каждой странице сайта.

Пока еще не разбирался с шаблонами для публикации, но надеюсь привести весь сайт к одному
виду...

И есть несколько багов -- почему-то относительные ссылки публикуются неправильно, и
неправильно генерируются имена файлов при использовании только русского текста в
заголовках.  Так что все это будет пофиксено после разбора со связкой blorg/org-mode.

* DONE Обновление статьи про Emacs + Scheme               :article:emacs:scheme:
  CLOSED: [2008-08-04 Mon 12:20]

Выложено обновление для [[http://xtalk.msk.su/~ott/ru/writings/emacs-devenv/][статьи про использование Emacs для работы с языком Scheme]] --
добавлено краткое описание настройки пакета SLIME для работы со Scheme.

* DONE Добавил раздел про Erlang                                   :site:erlang:
  CLOSED: [2008-08-04 Mon 10:41]

Добавил на сайт [[http://xtalk.msk.su/~ott/ru/erlang/][раздел про программирование на Erlang]].  В этом разделе будут публиковаться
различные записки, связанные с программированием на Erlang

