#+TITLE:       Alex Ott's Page. Новости сайта
#+SUBTITLE:    Новости
#+BLOG_URL:    http://xtalk.msk.su/~ott/ru/news/
#+PUBLISH_DIR: /home/ott/projects/my-page-muse/ru/news/
#+ENCODING:    utf-8
#+LANGUAGE:    ru
#+FEED_TYPE:   atom
#+HOMEPAGE:    http://xtalk.msk.su/~ott/ru/
#+KEYWORDS:    alex ott blog news articles emacs новости статьи емакс программирование
#+HTML_CSS:    web.css

* DONE Добавил раздел про Erlang                                   :site:erlang:
  CLOSED: [2008-08-04 Mon 10:41]

Добавил на сайт [[../erlang/][раздел про программирование на Erlang]].  В этом разделе будут публиковаться
различные записки, связанные с программированием на Erlang 

* DONE Обновление статьи про Emacs + Scheme               :article:emacs:scheme:
  CLOSED: [2008-08-04 Mon 12:20]

Выложено обновление для [[../writings/emacs-devenv/][статьи про использование Emacs для работы с языком Scheme]] --
добавлено краткое описание настройки пакета SLIME для работы со Scheme.

* DONE Прикрутил к сайту ленту новостей через blorg                 :site:emacs:
  CLOSED: [2008-08-04 Mon 12:32]

С помощью [[http://lumiere.ens.fr/~guerry/u/blorg.html][blorg]] прикрутил к сайту публикацию ленты новостей из файлов org-mode.  Так что
можете подписаться и получать новости об обновлениях статей и т.п.  Ссылки на
соответствующие ленты находятся на каждой странице сайта.

Пока еще не разбирался с шаблонами для публикации, но надеюсь привести весь сайт к одному
виду...

И есть несколько багов -- почему-то относительные ссылки публикуются неправильно, и
неправильно генерируются имена файлов при использовании только русского текста в
заголовках.  Так что все это будет пофиксено после разбора со связкой blorg/org-mode.

* DONE Драфт статьи про Emacs + Erlang                            :emacs:erlang:
  CLOSED: [2008-08-06 Wed 15:27]

выложил на сайт драфт [[../writings/emacs-devenv/EmacsErlang.html][статьи про работу с Erlang в Emacs]].  В следующей вресии будет
добавлено описание erlware-mode и distel.
